#!/usr/bin/env python3
#-
# SPDX-License-Identifier: BSD-2-Clause
#
"""Keep AI attribution out of everything this repository publishes.

The rule is the owner's: nothing here credits a tool for the work. No line in a commit
message, no footer in a pull request, no "generated by" in a document, no co-author
trailer, no link to an assistant's session. The reason is not modesty - a reader of this
repository is being asked to trust measurements taken on one appliance, and a provenance
line that names a tool instead of a person is a claim about where the evidence came from
that nobody can check.

WHY THIS FILE EXISTS AT ALL, and it is the same reason check-code-language.py exists.
The Arabic rule had a checker from early on and has never been broken. This rule had
none, and was broken twice in one day - both times by a footer appended to text that was
otherwise correct, both times noticed by the owner rather than by CI. A rule nobody can
enforce is a rule somebody has to remember, and remembering is not a mechanism.

WHAT IT CANNOT SEE. It reads this working tree and, when asked, the commit messages on a
branch. It does not read GitHub: a pull request body, an issue comment or a review
comment lives on the server and never passes through a checkout, so nothing here can
check one. Those are the places both breaches happened. Treat a green run as "the tree
and the commits are clean" and nothing more.

THE ONE EXEMPTION, and it is this file. A checker for a phrase has to carry the phrase,
so tools/check-attribution.py matches its own patterns on every line of the table below.
That is named here, in SELF_EXEMPT, and skipped by path - the same way exempt() in
check-code-language.py names the translation catalogues it must not read as code. It is
not hidden behind an encoding or assembled from fragments at runtime: a reader should be
able to see what is searched for by reading the search list.

AND THERE IS DELIBERATELY NO IGNORE FILE. check-code-language.py honours
.code-language-ignore because a repository can legitimately carry a file of another
language. Nothing legitimately carries an attribution footer, so an ignore list here
would only ever be used to let one through - and it would be the first thing reached for
at the moment the rule was being broken. The absence is the point.

    tools/check-attribution.py [paths...] [--commits <range>]

With --commits, also check every commit message in that range - origin/main..HEAD in CI.
A range that cannot be resolved is an error rather than a pass: a check that silently
examined nothing is worse than no check, because it reports success.

Exit status is 0 when clean, 1 when something must come out, 2 on a usage error.
"""
import pathlib
import subprocess
import sys

# What AI attribution looks like, and why each one is here. Matched case-insensitively
# against every line, so a pattern is a lowercase substring rather than a regex: there is
# no pattern here that needs alternation, and a plain substring is a thing a reader can
# check against a line by eye.
MARKERS = (
    ('generated by', 'the footer form, as appended to five issue comments on 2026-10-04'),
    ('generated with', 'the other footer form, usually behind a robot emoji'),
    ('co-authored-by: claude', 'the trailer form, which git shows as a second author'),
    ('co-authored-by: anthropic', 'the same, under the vendor name'),
    ('claude.ai', 'a link to an assistant session, which is a provenance claim'),
    ('claude.com', 'the same, under the other domain'),
    ('claude code', 'the product name, which has no reason to appear here'),
    ('claude opus', 'a model name, likewise'),
    ('anthropic', 'the vendor name, likewise'),
    ('\U0001f916', 'the robot emoji, which is only ever there to mark a footer'),
)

SKIP_DIRS = {'.git', '__pycache__', 'node_modules'}
BINARY = {'.png', '.jpg', '.jpeg', '.gif', '.ico', '.pdf', '.zip', '.gz', '.mo'}

# This file, and nothing else. See the docstring.
SELF_EXEMPT = 'tools/check-attribution.py'


def hits(line):
    """Every marker present in this line, with the reason it is a marker."""
    low = line.lower()
    return [(marker, why) for marker, why in MARKERS if marker in low]


def check_tree(roots):
    failures = 0
    checked = 0
    exempted = 0

    for root in roots:
        base = pathlib.Path(root)
        for path in sorted(base.rglob('*')):
            if not path.is_file() or any(p in SKIP_DIRS for p in path.parts):
                continue
            if path.suffix.lower() in BINARY:
                continue
            relative = path.relative_to(base)
            if relative.as_posix() == SELF_EXEMPT:
                exempted += 1
                continue
            try:
                text = path.read_text(encoding='utf-8')
            except (UnicodeDecodeError, OSError):
                continue
            checked += 1
            for number, line in enumerate(text.splitlines(), 1):
                for marker, why in hits(line):
                    print('%s:%d: %r - %s' % (path, number, marker, why))
                    failures += 1

    return failures, checked, exempted


def check_commits(rng):
    """Every commit message in a range. Returns (failures, count), or None if unresolvable."""
    try:
        out = subprocess.run(['git', 'log', '--format=%H%x00%B%x00', rng],
                             capture_output=True, text=True, check=True).stdout
    except (subprocess.CalledProcessError, OSError):
        return None

    failures = 0
    count = 0
    records = [r for r in out.split('\x00\n') if r.strip()]
    for record in records:
        sha, _, body = record.partition('\x00')
        count += 1
        for number, line in enumerate(body.splitlines(), 1):
            for marker, why in hits(line):
                print('commit %s, message line %d: %r - %s'
                      % (sha[:12], number, marker, why))
                failures += 1
    return failures, count


def main(argv):
    args = argv[1:]
    rng = None
    if '--commits' in args:
        i = args.index('--commits')
        if i + 1 >= len(args):
            print('--commits needs a range, for example origin/main..HEAD')
            return 2
        rng = args[i + 1]
        del args[i:i + 2]
    roots = [a for a in args if not a.startswith('-')] or ['.']

    failures, checked, exempted = check_tree(roots)

    commits = None
    if rng is not None:
        commits = check_commits(rng)
        if commits is None:
            print('cannot resolve %s - the commits were not checked.' % rng)
            print('In CI this means the checkout has no history: give that job')
            print('fetch-depth: 0. Reporting failure rather than a pass, because a check')
            print('that examined nothing must not report success.')
            return 1
        failures += commits[0]

    if failures:
        print()
        print('%d line(s) carry AI attribution.' % failures)
        print('Take the line out, and the separator above it with it. Nothing here credits')
        print('a tool for the work - see CONTRIBUTING.md.')
        return 1

    where = '%d file(s) checked, %d exempted' % (checked, exempted)
    if commits is not None:
        where += ', %d commit message(s) in %s' % (commits[1], rng)
    print('%s, no AI attribution.' % where)
    print('Note: this cannot see pull request bodies, issue comments or review comments.')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
